<a href="https://colab.research.google.com/github/aminehd/AminehTechnicalWritings/blob/main/SamplingStatsAndDistros.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Outline
- Introduction (Purpose + scope)
- Body
  - sample summary statistics and examples (coefficients of fitted model)
  - load data and showcase
  - Sampling distribution of summary statistics. (use sample mean as example)
  - Expected value of summary statistics
  - Variance of summary statistic
  - Variance within a sample vs variance of a given stat over samplings
  - Standrad Error of stats and confidence interval. (SE(beta0))
  - F-test (within groups variance vs between group variance)
- Conclusion:

## Git setup and data load

In [1]:
import google.colab
repo_path = 'AminehTechnicalWritings'
!git -C $repo_path pull origin || git clone https://github.com/aminehd/AminehTechnicalWritings/ $repo_path
local_clone = '/content/' + repo_path
!git config --global user.email "amineh.dadsetan@gmail.com"
!git config --global user.name "Amineh Dadsetan"

fatal: cannot change to 'AminehTechnicalWritings': No such file or directory
Cloning into 'AminehTechnicalWritings'...
remote: Enumerating objects: 171, done.
remote: Counting objects: 100% (168/168), done.
remote: Compressing objects: 100% (87/87), done.
remote: Total 171 (delta 95), reused 140 (delta 79), pack-reused 3
Receiving objects: 100% (171/171), 3.16 MiB | 15.12 MiB/s, done.
Resolving deltas: 100% (95/95), done.


In [2]:
import numpy as np
files = np.load(local_clone + '/population.npz')
# sample = np.load(local_clone + '/sample.npy'
population = files['arr_0']
population.shape

(300000, 2)

### Summary Statistic

Previously we explained the concept of population and the concept of sample. Basically we have one population (e.g., population of American people) but we can sample a subset in many ways (e.g., sample of America people under age 18, sample of American people living in new your, etc).

In fact if N is population size, there is $2^N$ samples.

Now a statistic or measure can be defined on the whole population as well as any given sample. A statistic or a measure in mathematic is a generalization of concepts such as lenght or heigh for a given set. Since samples and the population are sets, we can define such things on them. A well known one is mean. Thus you can think of population mean or any given sample mean.

So far it was fairly easy to explain things. But it gets a bit trickier when we wanna talk the distribution of such measures over allll samples and compare them with the value of measure on the poulation.

The motivation behind sampling is that population is too big and it is virtually impossible to calculate the mean for the whole population. Let's say as a minister of something you need the average age of your population.  

Let's look at the population mean and sample mean for the data set we have created in previous notebooks.There are only 30 distinct x values in the pupolation data. Let pick a subset of such distinct x.




In [5]:
print(population[:, 0])
len(population[:,0])
distinct_xs = np.unique(population[:, 0])
len(distinct_xs)
x_samp_index = np.linspace(0, len(distinct_xs)-1, 100).astype(int)
x_samples = distinct_xs[x_samp_index]
x_samples
n_repeat = len(population[:,0]) // len(distinct_xs)
n_repeat

[ 1.  1.  1. ... 10. 10. 10.]


10000

We sampled 100 distinct x and stored them in `x_samples`. There are several observations for each x in sample and thus several responses in the population. Thus we can have several sampling with given `x_samples`. Let's pick one such and plot it:
Next thing is you wanna randomly pick y's that are response to these x's. Not easiest to implement now. think of abstraction HERE!!!

In [14]:
rand_gen = np.random.default_rng(2)
def sample_response(x_sams, population, rand_gen):
  for x in x_sams:
    # generate integer between 0 to n_repeat
    index = rand_gen.integers(0, n_repeat)
    yield (population[x * n_repeat + index, 0], population[x * n_repeat + index, 1],)

y_for_x_samples = np.array(list(sample_response(x_samp_index, population, rand_gen))
)


# YAY HERE!! plot the sample distro and mark it's mean with red

In [21]:
import matplotlib.pyplot as plt
fig, ax = plt.subplots(ncols=2)
ax[0].scatter(y_for_x_samples[:,0], y_for_x_samples[:,1] )
# ax[1] = ax[0].twinx()
# ax[1].axhlhine(y=np.mean(y_for_x_samples[:,1]), color='r')
ax[1].hist(y_for_x_samples[:,1], bins=40)

(array([2., 1., 2., 2., 5., 1., 2., 0., 4., 3., 4., 3., 6., 1., 2., 4., 3.,
        1., 2., 1., 4., 4., 3., 2., 4., 1., 5., 3., 1., 4., 2., 1., 2., 1.,
        2., 5., 3., 2., 1., 1.]),
 array([ 4.93218929,  5.42660439,  5.92101948,  6.41543458,  6.90984967,
         7.40426477,  7.89867986,  8.39309496,  8.88751005,  9.38192515,
         9.87634024, 10.37075534, 10.86517043, 11.35958553, 11.85400062,
        12.34841572, 12.84283081, 13.33724591, 13.831661  , 14.3260761 ,
        14.82049119, 15.31490628, 15.80932138, 16.30373647, 16.79815157,
        17.29256666, 17.78698176, 18.28139685, 18.77581195, 19.27022704,
        19.76464214, 20.25905723, 20.75347233, 21.24788742, 21.74230252,
        22.23671761, 22.73113271, 23.2255478 , 23.7199629 , 24.21437799,
        24.70879309]),
 <BarContainer object of 40 artists>)



https://en.wikipedia.org/wiki/Sampling_distribution
start with mu but get to beta_i HERE!!!

The concept of unbiased estimator pops up one more time. HERE!!!


Then we look at expected value of sample statistices over multiple sampling. Also we look at variance of stuff within sample, and variance of sample stat over several samplings. This indeed is an intersting case when sample stat is defined to be the mean of sample. HERE!!!




notebook we try to look at the model coefficients ( 𝛽𝑖 's ) as summary statistics defined on samples. You can also think of them as measures since samples are subsets.



These can help understand concept of Standard Error and F-test better.